public class UserInfo
{
    public int ap;
    public int ap_heal_sec;
    public int ap_max;
    public int ap_next_sec;
    public int arthur_rank;
    public int bp;
    public int bp_heal_sec;
    public int bp_max;
    public int bp_next_sec;
    public int card_extend_limit;
    public int card_max;
    public int card_max_extend;
    public int card_num;
    public int coin;
    public int coin_free;
    public string comment;
    public sbyte enter_state;
    public int exp;
    public int fame;
    public sbyte first_arthur_type;
    public int fp;
    public int friend_extend_limit;
    public int friend_max;
    public int friend_max_extend;
    public int gold;
    public string inviteid;
    public JobInfo[] jobs;
    public long leader_card_uniqid;
    public int leader_cardid;
    public int lv;
    public string name;
    public sbyte navi_type;
    public int next_lv_exp;
    public int now_lv_exp;
    public sbyte premium_service_grade;
    public int userid;
}